### ISSUE TITLE
😋 为什么在最上面多了2px的间距?

### ISSUE THREAD

**Issue by yuxino** [LonelyLiaR/hexo-theme-nameless#1]
看到[这个人](https://woaibn.github.io/)的网站最上面感觉怪怪的

**Comment by glitchboyl** [comment]
那2px是故意的。感觉加了这2px之后很有逼格...

**Comment by yuxino** [comment]
是啊。不过用你的这个主题的那个人的就比较难看了。

**Comment by glitchboyl** [comment]
其实还好, 是我主题的问题。 
到时候再改改, 现在没什么灵感
